"""schema inicial catalogo

Revision ID: 842468ad06ea
Revises:
Create Date: 2026-10-01 21:13:24.776542

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "842468ad06ea"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categoria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categoria")),
        sa.UniqueConstraint("nome", name=op.f("uq_categoria_nome")),
    )
    op.create_table(
        "produto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo_barras", sa.String(length=14), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("embalagem", sa.String(length=30), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["categoria_id"], ["categoria.id"], name=op.f("fk_produto_categoria_id_categoria")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_produto")),
    )
    with op.batch_alter_table("produto", schema=None) as batch_op:
        batch_op.create_index(
            "uq_produto_codigo_ativo",
            ["codigo_barras"],
            unique=True,
            sqlite_where=sa.text("deleted_at IS NULL"),
        )

    op.create_table(
        "movimentacao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("produto_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "ENTRADA",
                "SAIDA",
                "AJUSTE",
                name="tipomovimentacao",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("observacao", sa.String(length=200), nullable=True),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(tipo = 'AJUSTE' AND quantidade <> 0) OR (tipo <> 'AJUSTE' AND quantidade > 0)",
            name=op.f("ck_movimentacao_quantidade_por_tipo"),
        ),
        sa.ForeignKeyConstraint(
            ["produto_id"], ["produto.id"], name=op.f("fk_movimentacao_produto_id_produto")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movimentacao")),
    )
    with op.batch_alter_table("movimentacao", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_movimentacao_criado_em"), ["criado_em"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_movimentacao_produto_id"), ["produto_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movimentacao", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movimentacao_produto_id"))
        batch_op.drop_index(batch_op.f("ix_movimentacao_criado_em"))

    op.drop_table("movimentacao")
    with op.batch_alter_table("produto", schema=None) as batch_op:
        batch_op.drop_index("uq_produto_codigo_ativo", sqlite_where=sa.text("deleted_at IS NULL"))

    op.drop_table("produto")
    op.drop_table("categoria")
    # ### end Alembic commands ###
